// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN09s7JQlIuh4sX0pGGFVOJFbbIm4eyjY',
    appId: '1:858369127304:web:f6b4b3589f73ff35a0403d',
    messagingSenderId: '858369127304',
    projectId: 'azmy-qatra-blood-donation',
    authDomain: 'azmy-qatra-blood-donation.firebaseapp.com',
    databaseURL: 'https://azmy-qatra-blood-donation.firebaseio.com',
    storageBucket: 'azmy-qatra-blood-donation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN09s7JQlIuh4sX0pGGFVOJFbbIm4eyjY',
    appId: '1:858369127304:android:f6b4b3589f73ff35a0403d',
    messagingSenderId: '858369127304',
    projectId: 'azmy-qatra-blood-donation',
    authDomain: 'azmy-qatra-blood-donation.firebaseapp.com',
    databaseURL: 'https://azmy-qatra-blood-donation.firebaseio.com',
    storageBucket: 'azmy-qatra-blood-donation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN09s7JQlIuh4sX0pGGFVOJFbbIm4eyjY',
    appId: '1:858369127304:ios:f6b4b3589f73ff35a0403d',
    messagingSenderId: '858369127304',
    projectId: 'azmy-qatra-blood-donation',
    authDomain: 'azmy-qatra-blood-donation.firebaseapp.com',
    databaseURL: 'https://azmy-qatra-blood-donation.firebaseio.com',
    storageBucket: 'azmy-qatra-blood-donation.appspot.com',
  );
}
